name: SeineSailor

permissions:
  contents: read
  pull-requests: write
  issues: write
  discussions: write

on:
  issues:
    types: [ opened ]
  issue_comment:
    types: [ created ]
  pull_request:
  pull_request_target:
    types: [ opened, synchronize, reopened ]
  pull_request_review_comment:
    types: [ created ]
  discussion:
    types: [ created ]
  discussion_comment:
    types: [ created ]

concurrency:
  group:
    ${{ github.repository }}-${{ github.event.number || github.head_ref ||
    github.sha }}-${{ github.workflow }}-${{ (github.event_name ==
    'pull_request' || github.event_name == 'pull_request_target') && 'pr' || 'comment' }}
  cancel-in-progress: ${{ github.event_name == 'pull_request_target' }}

jobs:
  seinesailor:
    if: |
      github.event_name == 'pull_request' ||
      github.event_name == 'pull_request_target' ||
      (contains(github.event.comment.body, '@SeineSailor') && (
        github.event_name == 'issue_comment' || 
        github.event_name == 'pull_request_review_comment' ||
        github.event_name == 'discussion_comment')) ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@SeineSailor')) ||
      (github.event_name == 'discussion' && contains(github.event.discussion.body, '@SeineSailor'))
    runs-on: ubuntu-latest
    steps:
      - name: Check for mention outside of quotes in comments
        id: check_mention
        env:
          COMMENT_BODY: ${{ github.event.comment.body }}
        run: |
          echo "checking for mention outside of quotes"
          if echo "$COMMENT_BODY" | grep -v '^>' | grep -q '@SeineSailor'; then
            echo "mention_outside_quotes=true" >> $GITHUB_ENV
          else
            echo "mention_outside_quotes=false" >> $GITHUB_ENV
          fi
      - name: Run SeineSailor
        uses: SeineAI/SeineSailor@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          IBM_CLOUD_API_KEY: ${{ secrets.IBM_CLOUD_API_KEY }}
          WATSONX_PROJECT_ID: ${{ secrets.WATSONX_PROJECT_ID }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          debug: true
          tag: latest # use latest docker image for development