name: payload test
# This workflow is for inspecting the payload of various triggering event.

permissions:
  contents: read
  pull-requests: write
  issues: write
  discussions: write

on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created, edited]
  pull_request:
    types: [opened, synchronize, reopened, review_requested]
  pull_request_target:
    types: [opened, synchronize, reopened, review_requested]
  pull_request_review:
    types: [submitted, edited]
  pull_request_review_comment:
    types: [created, edited]
  discussion:
    types: [created, edited]
  discussion_comment:
    types: [created, edited]

jobs:
  payload_test:
    if: |
      contains(github.event.comment.body, '@SeineSailor') ||
      (github.event_name == 'issues' && contains(github.event.issue.body, '@SeineSailor')) ||
      ((github.event_name == 'pull_request' || 
      github.event_name == 'pull_request_target') && contains(github.event.pull_request.body, '@SeineSailor')) ||
      (github.event_name == 'pull_request_review' && contains(github.event.review.body, '@SeineSailor')) ||
      (github.event_name == 'discussion' && contains(github.event.discussion.body, '@SeineSailor'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref || github.head_ref }}
      - name: Print event payload
        run: cat $GITHUB_EVENT_PATH
      - name: Print event repo_name
        run: echo $GITHUB_REPOSITORY